version: "3"

networks:
  backend:
    driver: bridge

volumes:
  my-db:

services:
  mysql:
    image: mysql:8.0.22
    container_name: mydb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - backend
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  flask_app:
#    build:
#      dockerfile: Dockerfile
#      context: .
#      args:
#        BUILD_ENV: $BUILD_ENV
    image: sample-flask-project_flask_app:latest
    container_name: flask_app
    expose:
      - '5000'
    environment:
      - FLASK_DEBUG=$FLASK_DEBUG
      - DB_URL=$DB_URL
    ports:
      - "5000:5000"
    network_mode: bridge

